# Generated by Django 3.1.4 on 2020-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_avaibility_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='dogs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='parking',
            field=models.BooleanField(default=True),
        ),
    ]
