# Generated by Django 3.1.4 on 2020-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20201220_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='balcony',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='doublebed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='kingsize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='roomservice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='seeview',
            field=models.BooleanField(default=True),
        ),
    ]
