# Generated by Django 3.1.4 on 2020-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20201220_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max_people',
            new_name='beds',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='min_people',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='dogs',
        ),
        migrations.RemoveField(
            model_name='room',
            name='doublebed',
        ),
        migrations.RemoveField(
            model_name='room',
            name='kingsize',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='parking',
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('ST', 'STANDARD'), ('DEL', 'DELUXE'), ('SUI', 'SUITE')], default='hello', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
