# Generated by Django 3.1.4 on 2020-12-21 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor', '0005_auto_20201221_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='enddate',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='startdate',
            new_name='check_out',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='profile',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
